language: cpp
dist: bionic
compiler:
  - gcc

cache: packages

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt
  - sudo apt install -qq qt5-qmake qt5-default libqt5svg5-dev libqwt-qt5-dev
  # Check dead links
  #- sudo apt-get install -qq npm
  #- npm config set strict-ssl false
  #- sudo npm install -g markdown-link-check
  # cppcheck
  - sudo apt install -qq cppcheck
  # sloccount
  - sudo apt install -qq sloccount
  # valgrind
  - sudo apt install -qq valgrind 
  # Check dead links
  #- rm .travis.yml
  #- ./scripts/check_dead_links || true
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Get my folder
  - my_github=${PWD##*/}  
  # GSL and other GitHubs
  - cd ..
  - git clone https://github.com/Microsoft/GSL
  - git clone -b develop https://github.com/richelbilderbeek/boost_graph_cookbook_1
  - git clone -b develop https://github.com/richelbilderbeek/BrainWeaver
  - git clone -b develop https://github.com/richelbilderbeek/ConceptMap
  - git clone -b develop https://github.com/richelbilderbeek/plane
  - git clone https://github.com/richelbilderbeek/QEventLogger
  - git clone -b develop https://github.com/richelbilderbeek/QtConceptMap
  - git clone -b develop https://github.com/richelbilderbeek/QtKeyboardFriendlyGraphicsView
  - git clone -b develop https://github.com/richelbilderbeek/RibiClasses
  - git clone -b develop https://github.com/richelbilderbeek/RibiLibraries
  - git clone -b develop https://github.com/richelbilderbeek/StyleSheetSetter
  - cd $my_github

services:
 - xvfb

script: 
  - ./build_other_githubs
  # Build console test
  - qmake -qt=qt5 BrainWeaverRuffian.pro
  - travis_wait 20 make --silent debug
  - ./BrainWeaverRuffian
  # cppcheck, be mild
  - cppcheck --quiet --error-exitcode=0 . 
  #- cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./do_oclint
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null

after_success:
  - bash <(curl -s https://codecov.io/bash)
